export const idfObjects = {
  data: [
    {
      id: 457,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Wall001",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "SPHW",
        A6: "Outdoors",
        A5: "Tung",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 459,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Wall002",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "SPHW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 461,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Wall003",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "SPHW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 463,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Wall004",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "SPHW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 465,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Flr001",
        A2: "Floor",
        A3: "FLOOR38",
        A4: "SPHW",
        A6: "Surface",
        A7: "Zn001:Flr001",
        A8: "NoSun",
        A9: "NoWind",
        N1: 1,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 466,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn001:Roof001",
        A2: "Roof",
        A3: "ROOF31",
        A4: "SPHW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 467,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Wall001",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 469,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Wall002",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 471,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Wall003",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 473,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Wall004",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 475,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Flr001",
        A2: "Floor",
        A3: "FLOOR38",
        A4: "DPW",
        A6: "Surface",
        A7: "Zn002:Flr001",
        A8: "NoSun",
        A9: "NoWind",
        N1: 1,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 476,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn002:Roof001",
        A2: "Roof",
        A3: "ROOF31",
        A4: "DPW",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 477,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Wall001",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWB",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 479,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Wall002",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWB",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 481,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Wall003",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWB",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 483,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Wall004",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWB",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 485,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Flr001",
        A2: "Floor",
        A3: "FLOOR38",
        A4: "DPWB",
        A6: "Surface",
        A7: "Zn003:Flr001",
        A8: "NoSun",
        A9: "NoWind",
        N1: 1,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 0,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 486,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn003:Roof001",
        A2: "Roof",
        A3: "ROOF31",
        A4: "DPWB",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 10,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 487,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn004:Wall001",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWD",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 0,
            N4: 0,
            N5: 10,
          },
          {
            N3: 0,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
    {
      id: 489,
      document_id: 4,
      class_id: 929,
      class_name: "BuildingSurface:Detailed",
      fields: {
        A1: "Zn004:Wall002",
        A2: "Wall",
        A3: "EXTERIOR",
        A4: "DPWD",
        A6: "Outdoors",
        A8: "SunExposed",
        A9: "WindExposed",
        N1: 0.5,
        N2: 4,
      },
      extensions: {
        vertices: [
          {
            N3: 10,
            N4: 0,
            N5: 10,
          },
          {
            N3: 10,
            N4: 0,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 0,
          },
          {
            N3: 10,
            N4: 10,
            N5: 10,
          },
        ],
      },
      category: null,
      from_template: 0,
      selected_object_id: null,
    },
  ],
  found_rows: 54,
};
